### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#30]
# Story
## User story
As an end user, I want to have the documentation about the tool and research done to build it 
## Tasks

- Final report first part

- Requirements to build and run the project

- Readme with procedure to run the tool

## Acceptance criteria

- [ ] Final report finished

- [ ] Final presentation finished

- [ ] Tool documentation finished

**Comment by fayanpardo** [comment]
Requirements to run the Tool:

- Google account with access to a project in GCP

- Google SDK with compute module locally installed

- Ethereum geth and puppeth tools installed locally (can be installed with a makefile or config script)

- Python libraries: lxml, pandas, matplotlib, numpy 

- Install jq (can be installed with a makefile or config script)

- Install in /bin caliper with npm. Caliper needs web3

**Comment by XhorxhinaT** [comment]
@boxrhcp  It is unclear to me this point "Install in /bin caliper with npm." 
I saw the script and the commands are commented. We decided to run caliper locally am I right?

**Comment by fayanpardo** [comment]
Which script are we talking about? Yes we are running caliper locally but the easiest way to install it is with npm: https://www.npmjs.com/package/@hyperledger/caliper-cli
This is why the task #63 first needs to check if npm is installed.

From my OS which is MacOS when I install things with npm it installs the tool in the same folder were I am running the npm command, if i try to run caliper outside the folder i installed it i get errors. This is why I wrote "install caliper inside the bin/ folder of the repo", to avoid errors when executing. Bu as always if you see efficient and better ways to install things thats better solution!
