### ISSUE TITLE
[Subtask]Create VM deployment script

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#33]
---
due: 2020-01-12
---
# Subtask
## Detailed Description
We need to deploy a VM for each node, in order to make this possible we need a deployment script that will install all whats needed to run ethereum in the VM. 
This script will just install the dependencies needed to run an ethereum node or a bootnode
## Acceptance Criteria

- [ ] The code of the script runs without any errors (error handling correctly used).
- [ ] The script installs geth and puppeth
- [ ] Geth and puppeth can be run without issues after the execution of this script

## Associated story
#17

**Comment by fayanpardo** [comment]
This task is on hold, until we finish the research for GKE nodes use.

**Comment by fayanpardo** [comment]
You can continue with the task!

**Comment by fayanpardo** [comment]
#47 
Karim: So what is missing now:

- the script still needs to take block size (currently a dummy param) DONE
- main script that runns this script several times DONE
- Algorithm to find optimal value
- result collection and aggregation DONE
