### ISSUE TITLE
Run-caliper script error handling

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#60]
# Task
## Detailed Description
We know that caliper will fail with certain configurations and we can not let the whole tool to fail. run-caliper.py should handle caliper errors. 
A variable must be added in the config file specifying the number of tries until we assume the execution of caliper failed.
This script should be also improved to delete the residual reports generated (possible benchmark reports created even though the execution failed) in case of failure. 
If the execution of caliper completely failed after trying a number of times this script should return this information to the main script, exit(-1) should be enough.
UPDATE 24/01: As of 23/01 this task was nearly fulfilled but we have seen that the caliper command does not fail if the benchmark prints a failure. A proposed solution for this can be seen in #74 
## Acceptance criteria
- [x] The code of the script runs without any errors (error handling correctly used)
- [x] The script runs caliper and in case of caliper error handle the error and retry the number of times specified in the config file
- [x] In case a failed caliper execution creates a failed residual report, the script must delete this report.
- [x] The script must return to the main script the error exit code in case caliper failed after a number of retries

### UPDATE 24/01

- [x] The script detects if the benchmark run successfully or not even if the caliper command was successful.

## Associated story
#22
