### ISSUE TITLE
GCP Instance template creation

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#61]
# Task
## Detailed Description
#33 MUST BE FINISHED BEFORE TAKING THIS TASK
We should create a script that creates a VM template. The process should be the following:
- Create a VM
- Deploy the script #33 and execute it.
- Stop the VM
- Create a VM template based on the VM created in the previous steps
This script should read from the config file the name of the template given by the user
## Acceptance Criteria
- [ ] The code of the script runs without any errors (error handling correctly used)
- [ ] The script creates in the configured project a VM template with the configured name
- [ ] Test if any VMs created from the instance template created by the script are able to execute geth and puppeth
## Associated story
#33 #13

**Comment by XhorxhinaT** [comment]
So is this finished @boxrhcp  @SantoshDhirwani ? I need to put it into the #72

**Comment by SantoshDhirwani** [comment]
@XhorxhinaT  yes this is finished. We are just waiting for @eltalkarim  to approve this PR as well but he hasn't responded to any messages yet. If he doesn't approve it tonight, I will merge it anyway tomorrow because it is blocking you as well.
