### ISSUE TITLE
SUT Script Improvements

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#62]
# Task
## Detailed Description
Make the the network id, the username and the password configurable in the config file so it can be read by SUT-deploy script.

Right now INSTANCE_LIST and INSTANCE_IP_LIST are extracting different information from the same list and we are assuming that the output will list in the same order. To avoid having future problems with our assumption INSTANCE_LIST and INSTANCE_IP_LIST should be merged into one.  it will also need changes in the gcloud command and script adaptation.
## Acceptance criteria
- [x] The code of the script runs without any errors (error handling correctly used).
- [x] The script receives as arguments the variables specified in the task.
- [x] The script gives the same result even with the changes applied.

## Associated story
#13

**Comment by ankushshr1993** [comment]
•	 **The script receives via parameters the number of nodes, gas limit and block interval.**
Please suggest if we should add these details through a config.json file already in the same folder through which it's taking directory name and password will that work or you have any other suggestions
•	 **The genesis file and they keystores created should be tested, creating a node that works with geth. Any account must be able to seal.**
Are we sure we need it to seal,as per my previous discussion with Karim, we agreed that we don’t need it so please @boxrhcp leo and @eltalkarim Karim confirm and help me with your suggestions

**Comment by fayanpardo** [comment]
Karim comment: there is no need to merge them in one list. just use the orderBy clause in the list commands and we won't have any problems

**Comment by SantoshDhirwani** [comment]
@boxrhcp  I think he meant` --sort-by`
https://cloud.google.com/sdk/gcloud/reference/compute/instances/list
