### ISSUE TITLE
Pre-requisites script

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#63]
# Task
## Detailed Description
We need to ease the installation of the tool to the user. We are already installing libraries and dependencies and we need to take care of them to facilitate the installation of the user.
We need a script that:

- Checks that Google SDK is installed, if not print a link to show where to download it / how to install it. If it is, configure the project written by the user in the config file.
- Check if geth and puppeth(docker also needed to be installed)  are installed, if not print a link to show how to install it.
- Check if jq (used in the SUT script) is installed, if not print a link to show how to install it.
- Check if npm is installed. If not print a link how to install it.
- Check if caliper is installed under /bin. If not, it will be installed with npm. 
- Run caliper bind to configure ethereum.
- Execute the template creation script #61
- If possible in this script, check that the python libraries needed are installed. If possible find an easy way to install these libraries. If it is not possible it should be enough with checking if these are installed or not.
## Acceptance criteria

- [ ] The code of the script runs without any errors (error handling correctly used)

- [ ] The code should print clear steps of how to install or at least show a link with clear documentation of how to install what is needed.

- [ ] If everything is installed, show a message that dependencies are fulfilled. 

- [ ] If after running the script everything is fulfilled, main.py must be able to run correctly without dependencies errors
## Associated story
#30  #72 
## Notes
the script is in #72
