### ISSUE TITLE
[Benchmark Algorithm] Implement algorithm to find the minimum configuration value

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#64]
# Task
## Detailed Description
We suppose that the user does not have knowledge about what is the minimum block interval and gaslimit values that he can try. 
Our tool should by benchmarking and handling the crashes find these minimum values. From these minimum values it will continue benchmarking step by step until finding the last improvement configuration values.
We need to implement this algorithm in main.py.
## Acceptance criteria
- [x] The code of the script runs without any errors (error handling correctly used)
- [x] The script must be able to detect the minimum block gas limit and block interval configuration where caliper can run without crashing or prompting errors.
- [x] The script must be able, after detecting the minimum combination configuration, to run benchmarks with the steps defined in the configuration file until the limit configured

## Associated story
#13
