### ISSUE TITLE
Automated genesis improvements

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#66]
# Task
## Detailed Description
We need to receive nodes, gas limit and block interval as argument and create the same number of accounts as nodes locally with geth. 
Like in task #18 It will create the genesis file taking block interval and gas limit as well as the accounts that should be added as sealers. This must be done without using puppeth
## Acceptance Criteria
- [x] The code of the script runs without any errors (error handling correctly used).
- [x] The script receives via arguments the number of nodes, gas limit and block interval.
- [x] The script must create a new genesis file with same number of accounts as nodes and the specified gas limit and block interval.
- [ ] The genesis file and they keystores created should be tested, creating a network that works with geth. Any account must be able to seal. 
## Associated story
#18 #54 #13

**Comment by ankushshr1993** [comment]
•	The script receives via parameters the number of nodes, gas limit and block interval.
Please suggest if we should add these details through a config.json file already in the same folder through which it's taking directory name and password will that work or you have any other suggestions
•	The genesis file and they keystores created should be tested, creating a node that works with geth. Any account must be able to seal.
Are we sure we need it to seal,as per my previous discussion with Karim, we agreed that we don’t need it so please @boxrhcp leo and @eltalkarim Karim confirm and help me with your suggestions

**Comment by fayanpardo** [comment]
Sorry for typo, I updated the requirement form parameters to arguments. The SUT will execute this script and at least gaslimit and interval will be changing constantly every benchmark.

Yes, we need all the nodes to seal. I was not in the call with Karim but if you look the SUT deployment script, we are adding every account as sealer following the puppeth interface. This script would avoid using puppeth and, without puppeth, we avoid possible errors that we can get while creating the genesis file (we already had a lot while developing) and we avoid having errors with the genesis file in case puppeth is updated in the future. It will also execute faster the deployment script.
Here there is a guide how "extraData" is filled: https://ethereum.stackexchange.com/questions/66927/how-to-set-sealers-in-genesis-block-extradata-for-a-clique-poa-network

I can see from our working deployment that the information of that post is correct. A script like this would be amazing for this project to make our tool more robust.

**Comment by ankushshr1993** [comment]
Update till now
The script is qualifying the first 3 criteria of the task, however, it's unable to mine after starting the node and waiting for the other node to sign.

Attached is the screenshot of the commands and steps with genesis.json used for testing
[Automated genesis error.docx](https://github.com/Cloud-Prototyping-WS-2019-20/cp_ws_1920/files/4130074/Automated.genesis.error.docx)

**Comment by XhorxhinaT** [comment]
Was discontinued
