### ISSUE TITLE
Implement algorithm of #76

### ISSUE THREAD

**Issue by fayanpardo** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#77]
# Task
## Detailed Description
We need to implement the benchmark algorithm specified in #76.
This task is divided into 2 tasks: #80 #81 
## Acceptance criteria

- [ ]  The algorithm executes the designed flow correctly. 

- [ ]  The code should handle errors correctly.

- [ ] The implementation should obtain the combination of block interval and block gas limit for the maximum TPS found in the execution

## Associated story
#76 #64 #65 #14
