### ISSUE TITLE
Adding a flag in main.py to ask user about printing output

### ISSUE THREAD

**Issue by SantoshDhirwani** [Cloud-Prototyping-WS-2019-20/cp_ws_1920#92]
# Task

Adding a flag in main.py to ask the user whether he/she wants the detailed output to be printed or not.

## Detailed Description
At present, a lot of things are being printed while running the tool which makes it very difficult for the user to understand exactly which step is being executed.
We need a flag in main.py for the user to specify if the detailed output is required to be printed or not (beneficial for debugging).
This task should add meaningful comments in main.py to print clearly which step is being executed at the moment.

## Acceptance Criteria

- [ ] The code must run without any errors.

- [ ] The execution must print clearly the steps of the execution and results of each step in case the flag is enabled for used mode.

- [ ] The execution must print all the output (as it is now) in case the flag is enabled for debug mode
